#!/usr/bin/env python3
"""Гл.10 PDF ч.3: Рейтинг Энергии + постэффекты фигур. status=draft."""
import sys
from pathlib import Path
sys.path.insert(0, str(Path(__file__).parent.parent))
from tools._lib.aku_io import save_aku, next_aku_id, now_iso, aku_path

AKUS = [
    dict(type="definition", strength="mandatory", topic="energy-rating",
        subtopics=["post-pattern-logic","trading-application"],
        statement_ru="Рейтинг Энергии коррекции (от -3 до +3) указывает, будет ли достигнут начальный уровень следующей за ней волной. Чем выше абсолютное значение — тем ниже вероятность полного отката. Применяется только к компактным (сжатым) фигурам. Таблица (волна завершается в восходящем / нисходящем направлении): Тройной Зигзаг +3/-3; Тройная Комбинация +3/-3; Тройная Плоская +3/-3; Двойной Зигзаг +2/-2; Двойная Комбинация +2/-2; Двойная Плоская +2/-2; Удлинённый Зигзаг +1/-2; Удлинённая Плоская +1/-1; Зигзаг/Неудавшаяся-b/Обыкновенная 0/0; Неудавшаяся-с -1/+1; Неправильная -1/+1; Неправильная (сильная) -2/+2; Двойная Тройка -2/+2; Тройная Тройка -2/+2; Подвижная Коррекция -3/+3.",
        quote="Рейтинг Энергии... указывает, будет, должен, может, не должен или не будет ее начальный уровень достигнут волной последующей... Рейтинги: Тройной Зигзаг +3/-3, Тройная Комбинация +3/-3, Тройная Плоская +3/-3, Двойной Зигзаг +2/-2, Двойная Комбинация +2/-2, Двойная Плоская +2/-2... Подвижная Коррекция -3/+3.",
        page="10-2", section="Рейтинг Энергии",
        aw="after compaction of corrective figure",
        cons="energy(triple_zigzag) = +3/-3 ; energy(triple_combo) = +3/-3 ; energy(double_zigzag) = +2/-2 ; energy(zigzag) = 0 ; energy(failed_c) = -1/+1 ; energy(moving_correction) = -3/+3",
        notes="В Треугольнике рейтинг Удлинённого Зигзага и Удлинённой Плоской = 0."),
    dict(type="rule", strength="mandatory", topic="energy-rating",
        subtopics=["post-pattern-logic","trading-application"],
        statement_ru="Интерпретация рейтинга Энергии: 0 → следующая волна от 0 до 100% длины предыдущей; ±1 → следующая ≤ 90% длины оцениваемой волны; ±2 → следующая ≤ 80%; ±3 → следующая ≤ 60-70%.",
        quote="1. Нулевой рейтинг Энергии (\"0\") не накладывает каких-либо специальных ограничений... 2. (+1 -1) – длина следующей завершённой волны того же Порядка должна быть не более 90% длины волны оцениваемой; 3. (+2, -2) – ... не более 80%...; 4. (+3, -3) – ... не более 60–70%.",
        page="10-2", section="Рейтинг Энергии / интерпретация",
        aw="predicting next wave retracement based on energy rating",
        cons="if |energy| == 0: next_wave_max = 1.0 * current ; if |energy| == 1: next_wave_max = 0.9 * current ; if |energy| == 2: next_wave_max = 0.8 * current ; if |energy| == 3: next_wave_max = 0.65 * current",
        notes=None),
    dict(type="rule", strength="mandatory", topic="post-pattern-logic",
        subtopics=["energy-rating","zigzag","combination"],
        statement_ru="Постэффект Двойного Зигзага (+2 ↑): следующая волна того же Порядка не должна достичь начального уровня фигуры (кроме: является волной-5 Терминального Импульса с Растянутой пятой).",
        quote="Если только эта фигура не является пятой волной Терминального Импульса с Растянутой пятой, следующая за ней волна не должна достичь ее начального уровня.",
        page="10-3", section="Двойной Зигзаг",
        aw="after double zigzag (+2 up direction)",
        cons="if not (terminal_impulse AND extended_5): next_wave NOT reach start(double_zigzag)",
        notes=None),
    dict(type="rule", strength="mandatory", topic="post-pattern-logic",
        subtopics=["energy-rating","flat"],
        statement_ru="Постэффект Неудавшейся-с (-1 ↑): следующая волна того же Порядка ДОЛЖНА достичь начального уровня. Если Неудавшаяся-с завершает коррективную фазу, следующая Импульсная волна должна быть больше предыдущей однонаправленной Импульсной.",
        quote="Следующая за Неудавшейся-с волна того же Порядка должна достигать ее начального уровня. Если Неудавшаяся-с завершает коррективную фазу, следующая за ней Импульсная волна должна быть больше предыдущей однонаправленной Импульсной волны.",
        page="10-5", section="Неудавшаяся-с",
        aw="after failed_c correction",
        cons="next_wave(same_order) MUST reach start(failed_c) ; if ends_corrective_phase: next_impulse > prev_impulse",
        notes=None),
    dict(type="rule", strength="mandatory", topic="post-pattern-logic",
        subtopics=["energy-rating","combination","x-wave"],
        statement_ru="Постэффект Подвижной Коррекции (-3 ↑): ДОЛЖНА следовать Растянутая волна Импульса (или Растянутая с-волна Зигзага/Плоской). Следующая импульсная волна должна быть БОЛЬШЕ 161.8% предыдущей импульсной (зачастую 261.8% и более). В Двойную или Тройную Тройку не должна развиваться.",
        quote="За Подвижной Коррекцией должна следовать Растянутая волна Импульса или Растянутая с-волна Плоской или Зигзага... длина ее должна составлять больше 161,8% длины предыдущего Импульса (зачастую 261,8% и более).",
        page="10-6", section="Подвижная Коррекция",
        aw="after moving correction (energy -3, upward wave)",
        cons="next_wave IS extended_impulse ; length(next_impulse) > 1.618 * prev_impulse ; NOT develops_into double_or_triple_three",
        notes="Важнейшее правило для торговли: Подвижная Коррекция предшествует самым мощным импульсам."),
    dict(type="rule", strength="mandatory", topic="post-pattern-logic",
        subtopics=["energy-rating","triangle","channeling"],
        statement_ru="Постэффект Ограничивающего Сужающегося Треугольника: за ним всегда следует 'выброс' (сильная резкая волна), который должен превысить уровень волны-b. Длина выброса зависит от типа: Горизонтальный ≈ ширина самой широкой волны (±25%); Неправильный — до 161.8% ширины; Подвижный — до 261.8%. Временная длина выброса ≈ времени от конца волны-e до пересечения линий тренда.",
        quote="За Сужающимся Треугольником всегда следует \"выброс\" (сильная, резкая волна)... Этот \"выброс\" должен заходить \"за\" (превышать) максимальный или минимальный уровень котировок, достигнутый в процессе формирования Треугольника, если только его направленность не противоположна направлению волны-b.",
        page="10-7", section="Сужающиеся Треугольники",
        aw="after contracting triangle completion",
        cons="thrust_length: horizontal => ~1.0 * widest_wave ; irregular => up_to 1.618 * widest ; moving => up_to 2.618 * widest ; thrust_time ~= time(wave_e to trendline_convergence)",
        notes="Рис. из Гл.10. Горизонтальное влияние вершины Треугольника длится 2-3 пробития."),
    dict(type="rule", strength="mandatory", topic="post-pattern-logic",
        subtopics=["energy-rating","impulse"],
        statement_ru="Постэффект Трендового Импульса: следующая волна того же Порядка не должна достичь начального уровня, если Импульс не является волной-5 или с-волной более крупной фигуры. С Растянутой 3-й: откат до ценовой зоны W4. С Растянутой 5-й: следующая ДОЛЖНА быть > 61.8% W5 — единственный случай, когда откат после Импульса обязателен более 61.8%.",
        quote="Следующая за Трендовым Импульсом волна не должна достичь его начального уровня, если только он сам не является волной-5 или волной-с более крупной фигуры... Импульс с Растянутой пятой – единственная из растянутых волн, после которой следующая волна того же Порядка должна быть больше 61,8% ее длины.",
        page="10-10", section="Трендовые Импульсы / Импульс с Растянутой пятой",
        aw="after trending impulse (any extension type)",
        cons="next_wave NOT reach start(impulse) unless wave_5_or_c ; if extended_3: retracement INTO wave_4_zone ; if extended_5: next_wave > 0.618 * length(wave_5)",
        notes="Критично для торговли: после Растянутой 5-й всегда сильный откат > 61.8% W5."),
    dict(type="rule", strength="mandatory", topic="post-pattern-logic",
        subtopics=["energy-rating","ending-diagonal"],
        statement_ru="Постэффект Терминального Импульса: следующая волна ДОЛЖНА достичь начального уровня Терминала не более чем за 50% времени его формирования (обычно около 25%). Терминал всегда завершает более крупную фигуру. Создаваемая им точка минимума/максимума удерживается примерно в течение минимум двух периодов формирования.",
        quote="Следующая за Терминальным Импульсом волна должна достичь его начального уровня не более чем за 50% времени его формирования; обычно это занимает примерно 25% этого времени.",
        page="10-10", section="Терминальные Импульсы",
        aw="after terminal impulse (ending diagonal) completion",
        cons="next_wave MUST reach start(terminal) ; time(reach_start) <= 0.5 * time(terminal_formation) ; level_held >= 2 * terminal_duration",
        notes="Самый надёжный постэффект для торговли: быстрый разворот после Терминала."),
    dict(type="rule", strength="mandatory", topic="post-pattern-logic",
        subtopics=["impulse","wave-identification","complexity-rule"],
        statement_ru="Неудавшаяся пятая волна возможна только при 3 условиях: A) данный Импульс является волной-5 более крупного Импульса; B) данный Импульс является с-волной на один Порядок выше; C) при крайне редких обстоятельствах — более крупная W3 испытывает Неудачу меньшей W5. Почти всегда W1 и W5 будут практически идентичны по цене и/или времени, или их соотношение = 61.8%.",
        quote="5-я волна может оказаться Неудавшейся только при одном из следующих обстоятельств: А. Если данная Импульсная фигура... сама является 5-й волной более крупной Импульсной фигуры... B. Если данная Импульсная фигура... является с-волной на один (и только один) Порядок выше.",
        page="11-4", section="Неудавшаяся пятая волна",
        aw="failed fifth wave detected",
        cons="context IN {wave_5_of_larger_impulse, c_wave_one_degree_higher, rare_large_3_fails} ; length(w1) APPROX length(w5) OR ratio = 0.618",
        notes="Рис.11-1: Неудавшаяся 5-я в конце 5-й волны. Рис.11-2: Неудавшаяся 5-я в с-волне."),
]

n = int(next_aku_id().split("-")[1]); saved = 0
for d in AKUS:
    aku_id = f"AKU-{n:04d}"
    aku = {
        "id": aku_id, "type": d["type"], "strength": d["strength"], "status": "draft",
        "topic": d["topic"], "subtopics": d["subtopics"],
        "statement_ru": d["statement_ru"], "statement_en": None,
        "source": {"book_id": "neely-mwe-1990", "page": d["page"],
                   "chapter": "Глава 10: Продвинутые Правила логики",
                   "section": d["section"], "figure_id": None,
                   "verbatim_quote": {"text": d["quote"], "language": "ru"}},
        "formalization": {"status": "draft", "applies_when": d["aw"],
                          "constraint": d["cons"], "formalization_notes": d["notes"]},
        "aliases": [], "related_aku": [], "contradicts_aku": [],
        "extends_aku": None, "supersedes_aku": None,
        "created_by": "claude", "created_at": now_iso(),
        "review_notes": "Извлечено Claude (PDF ч.3 Гл.10 стр.10-2..10-10, Гл.11 стр.11-4).",
        "requires_review": True,
    }
    save_aku(aku, aku_path("neely-mwe-1990", 10, "prodvinutye-pravila-logiki", aku_id))
    saved += 1; n += 1
print(f"Создано AKU (Гл.10 Энергия+постэффекты): {saved}")
