#!/usr/bin/env python3
"""Ручная формализация Гл.11-12 (in-session, без API). status=draft."""
import sys
from pathlib import Path
sys.path.insert(0, str(Path(__file__).parent.parent))
from tools._lib.aku_io import load_all_aku, save_aku

# id -> (status, applies_when, constraint, notes)
F = {
"AKU-0079": ("draft", "position IN ('wave_2','wave_4','wave_b','wave_d','wave_e','wave_x')",
    "structure(wave) != ':5'", "Эти позиции не могут быть Импульсом."),
"AKU-0080": ("draft", "pattern == 'trend_impulse' AND extended_wave == 1",
    "retrace(wave_2) <= 0.382 * length(wave_1)", "'Намного более 38.2%' — мягкая верхняя граница."),
"AKU-0081": ("draft", "pattern == 'trend_impulse' AND extended_wave == 1",
    "type(wave_2) != 'moving_correction'", None),
"AKU-0082": ("draft", "pattern == 'trend_impulse' AND extended_wave == 1",
    "length(wave_5) == min(length(wave_1), length(wave_3), length(wave_5))", None),
"AKU-0083": ("draft", "pattern == 'trend_impulse' AND extended_wave != 1",
    "length(wave_3) > length(wave_1)", None),
"AKU-0084": ("draft", "pattern == 'impulse' AND length(wave_1) == max(length(wave_1), length(wave_3), length(wave_5))",
    "retrace(wave_2) <= 0.382 * length(wave_1)", None),
"AKU-0085": ("draft", "pattern == 'impulse' AND degree(wave_1) >= 'polywave'",
    "degree(wave_2) >= 'polywave'", None),
"AKU-0086": ("draft", "position IN ('wave_1','wave_3','wave_5','zigzag.wave_a','zigzag.wave_c','flat.wave_c')",
    "structure(wave) == ':5'", "В позициях Метки импульса не может быть Коррективной фигуры."),
"AKU-0087": ("draft", "pattern == 'terminal_impulse' AND extended_wave == 1",
    "retrace(wave_2) <= 0.618 * length(wave_1) AND 0.382 * length(wave_1) <= length(wave_3) <= 0.618 * length(wave_1) AND length(wave_5) <= 0.99 * length(wave_3)", None),
"AKU-0088": ("draft", "pattern == 'flat' AND subtype == 'common'",
    "0.81 * length(wave_a) <= length(wave_b) <= 1.00 * length(wave_a) AND length(wave_c) >= length(wave_b) AND structure(wave_c) == ':5'", None),
"AKU-0089": ("draft", "pattern == 'triangle'",
    "length(wave_d) != max(length(a), length(b), length(c), length(d), length(e))", None),
"AKU-0090": ("draft", "pattern == 'triangle'",
    "not (any 3 of [a,b,c,d,e] are equal within 5% by price)", None),
"AKU-0091": ("draft", "pattern == 'contracting_triangle'",
    "for seg in [a,b,c,d]: type(seg) != 'contracting_triangle'", None),
"AKU-0092": ("draft", "pattern == 'triangle'",
    "for seg in [a,b,c,d]: type(seg) != 'triangle'", "Только волна-e может быть меньшим Треугольником."),
"AKU-0094": ("draft", "pattern == 'flat' AND subtype == 'irregular_failure'",
    "not reaches(end(wave_c), start_level(wave_b)) AND length(wave_b) > length(wave_a)", None),
"AKU-0095": ("draft", "pattern == 'moving_correction' AND position == 'post_pattern'",
    "length(next_segment) == max(length(all_segments(completed_pattern)))", None),
"AKU-0096": ("draft", "pattern == 'zigzag'",
    "structure(wave_a) == ':5' AND structure(wave_b) == ':3' AND retrace(wave_b) <= 0.618 * length(wave_a)", None),
"AKU-0097": ("draft", "pattern == 'zigzag' AND parent != 'triangle'",
    "type(wave_b) != 'moving_correction'", None),
"AKU-0098": ("draft", "pattern == 'horizontal_contracting_limiting_triangle'",
    "length(wave_d) < length(wave_c) AND length(wave_e) < length(wave_d) AND 0.382 * length(wave_a) <= length(wave_b) <= 2.618 * length(wave_a)", None),
"AKU-0099": ("draft", "pattern == 'nonlimiting_triangle' AND role != 'x_wave'",
    "completes_phase(larger_correction) == true", None),
"AKU-0100": ("draft", "pattern == 'expanding_triangle'",
    "next_pattern NOT IN ('extended_1','extended_2','extended_3','elongated_c') AND not ends_correction(['double','triple','combination'])", None),
"AKU-0101": ("draft", "pattern == 'expanding_triangle' AND position == 'post_pattern' AND role IN ('wave_c','wave_5')",
    "not reaches(next_wave, start_level(wave_e))", None),
"AKU-0102": ("draft", "pattern == 'expanding_limiting_triangle' AND position == 'wave_b'",
    "parent == 'flat' AND parent NOT IN ('zigzag', 'complex_correction_x', 'larger_triangle')", None),
"AKU-0105": ("draft", "pattern == 'expanding_limiting_horizontal_triangle'",
    "complexity(wave_e) == max AND duration(wave_e) == max AND length(wave_e) == max", None),
"AKU-0107": ("draft", "pattern == 'impulse'",
    "not breaks(wave_3, trendline(start(0), end(2)))",
    "Если откат после волны-2 не удерживается выше линии 0-2 → движение не импульсное."),
"AKU-0108": ("draft", "pattern == 'impulse'",
    "not breaks(wave_3, trendline(end(2), end(4))) AND (not breaks(wave_5, trendline(end(2), end(4))) OR subtype == 'terminal')", None),
"AKU-0109": ("draft", "pattern == 'impulse' AND position == 'post_pattern'",
    "breaks(next_move, trendline(end(2), end(4))) AND duration(until_break) <= duration(wave_5) AND retrace(next_move) >= 0.99 * length(wave_5)",
    "'Большая часть или вся' волна-5 откатывается."),
"AKU-0110": ("draft", "subtype == 'failure_5th' AND position == 'post_pattern'",
    "duration(retrace_whole_impulse) < duration(impulse) AND duration(to_exceed_end(failed_5th)) >= 2 * duration(impulse)", None),
"AKU-0111": ("draft", "position == 'wave_b' AND type(wave_b) == 'triangle'",
    "trendline(0, B) drawn_through end(wave_c) NOT end(wave_e)",
    "Линию 0-B вести через волну-c Треугольника, если через волну-e её пробьёт волна-c."),
"AKU-0112": ("draft", "position == 'wave_b' AND type(wave_b) == 'triangle'",
    "not exceeds(end(wave_e), end(wave_c))", "'Ложное' пробитие линии 0-B допустимо только очень кратко."),
"AKU-0113": ("draft", "pattern == 'terminal_impulse' AND position == 'post_pattern'",
    "reaches(next_move, extreme(wave_4))",
    "В 99% случаев рынок возвращается к началу волны-1 или ниже."),
"AKU-0114": ("draft", "pattern == 'impulse' AND extended_wave == 3",
    "parallel(channel_lines) == true OR nearly_parallel(channel_lines) == true", None),
"AKU-0115": ("draft", "pattern == 'zigzag' AND wave_c beyond parallel_line AND position == 'post_pattern'",
    "not reaches(next_wave, start_level(zigzag))", "Если откат < 61.8% — доп. следствия (цитата усечена)."),
"AKU-0116": ("draft", "pattern == 'impulse' AND extended_wave == 1",
    "length(wave_3) <= 0.618 * length(wave_1)", None),
"AKU-0117": ("draft", "pattern == 'impulse' AND extended_wave == 3",
    "length(wave_1) != 0.618 * length(wave_3)", "Внутреннее соотношение 61.8% между волнами 1 и 3 запрещено."),
"AKU-0118": ("draft", "pattern == 'impulse' AND extended_wave == 3",
    "length(wave_5) < 0.618 * length(wave_3)", None),
"AKU-0119": ("draft", "pattern == 'flat'",
    "length(wave_c) <= 1.382 * length(wave_a)", "Если c > 138.2% a → категория Удлинённой Плоской."),
"AKU-0120": ("draft", "pattern == 'zigzag'",
    "length(wave_c) >= 0.618 * length(wave_a)", "Если меньше — вероятно Треугольная b-волна / сторона Треугольника."),
"AKU-0121": ("draft", "classifying pattern",
    "(is_impulse IMPLIES monowave_count >= 5) AND (is_correction IMPLIES monowave_count >= 3)", None),
"AKU-0122": ("draft", "wave_status == 'missing'",
    "degree(missing_wave) == 'monowave'", None),
"AKU-0123": ("draft", "evaluating missing_wave possibility",
    "data_points >= 2 * minimum_data_points IMPLIES missing_wave_possible == false", None),
"AKU-0124": ("draft", "pattern == 'impulse' AND extended_wave == 3",
    "(is_complex(wave_4) IMPLIES length(wave_5) < length(wave_1)) AND (is_complex(wave_2) IMPLIES length(wave_5) <= length(wave_1))", None),
"AKU-0125": ("draft", "pattern == 'impulse' AND extended_wave == 5",
    "length(wave_5) >= min(1.000 * (length(wave_1) + length(wave_3)), 1.618 * length(wave_3)) AND length(wave_5) <= 2.618 * (length(wave_1) + length(wave_3))", None),
"AKU-0126": ("draft", "pattern == 'impulse'",
    "alternation(wave_2, wave_4, by='time' OR 'price' OR 'structure') == true", None),
"AKU-0127": ("draft", "pattern == 'impulse'",
    "retrace(end(wave_2)) <= 0.618 * length(wave_1)", "Часть волны-2 может уходить глубже, но ЗАВЕРШИТЬСЯ должна <= 61.8%."),
"AKU-0128": ("draft", "pattern == 'impulse' AND extended_wave == 3",
    "length(wave_3) > 1.618 * length(wave_1)", "Исключение: когда растягивается волна-5."),
"AKU-0129": ("draft", "pattern == 'impulse' AND subtype != 'terminal'",
    "structure(wave_3) != 'zigzag' AND structure(wave_5) != 'zigzag'", None),
"AKU-0130": ("draft", "pattern == 'impulse'",
    "has_extended_wave(impulse) == true", "Импульс обязан содержать Растянутую волну."),
"AKU-0131": ("draft", "multiple_valid_interpretations == true",
    "position == near_center_of(larger_pattern)",
    "Правило Обратной Логики: множественность счётов → рынок близок к центру более крупной фигуры (волна-b в волне-b и т.п.)."),
"AKU-0132": ("draft", "pattern == 'impulse' AND extended_wave == 1",
    "complexity(wave_2) == max AND duration(wave_2) == max", "'Почти всегда' — сильная эвристика-правило."),
"AKU-0133": ("draft", "pattern == 'double_zigzag'",
    "retrace(wave_b of first_zigzag) <= 0.618 * length(wave_a)", "Отличие двойного Зигзага от двойной Плоской (цитата усечена)."),
}

by_id = {a["id"]: a for a in load_all_aku()}
done = 0
for aku_id, (st, aw, cons, notes) in F.items():
    a = by_id.get(aku_id)
    if not a:
        print(f"  ПРОПУСК {aku_id}: не найден"); continue
    fp = a.pop("_filepath")
    a["formalization"] = {"status": st, "applies_when": aw, "constraint": cons, "formalization_notes": notes}
    save_aku(a, fp)
    done += 1
print(f"Формализовано: {done}/{len(F)}")
